### ISSUE TITLE
EBADPLATFORM

### ISSUE THREAD

**Issue by JAM-SEVEN** [MyEMS/myems#161]
请问只能在mac上跑吗？用npm install 出现EBADPLATFORM错误，提示
![image](https://user-images.githubusercontent.com/78628875/139361583-6813d0fb-ec4e-478a-a7bf-99e731296d2b.png)
我的平台
![image](https://user-images.githubusercontent.com/78628875/139361622-cbd4c942-e88b-4b55-9428-00a5abcd1564.png)

**Comment by hyh123a** [comment]
Linux 系统是支持的，目前一般是使用的Ubuntu 20.04进行的开发。

**Comment by hyh123a** [comment]
请删除myems/web/package-lock.json,重新在web目录下执行该命令npm install，可能是推送不小心把package-lock.json推送上去导致的，这个文件会在下次推送删除掉。

**Comment by JAM-SEVEN** [comment]
好滴好滴，谢谢回复~

**Comment by guangyuzhang** [comment]
Please try run 
`npm i fsevents@latest -f --save-optional`

**Comment by guangyuzhang** [comment]
v1.3.3中升级package.json中的版本号，解决了NPM安装错误

npm install error was fixed by new package.json in v1.3.3

https://github.com/MyEMS/myems/releases/tag/v1.3.3
