### ISSUE TITLE
Create Docker Images at Docker Hub

### ISSUE THREAD

**Issue by guangyuzhang** [MyEMS/myems#162]
Create docker images at docker hub 
https://hub.docker.com/u/myems

**Comment by guangyuzhang** [comment]
done

**Comment by guangyuzhang** [comment]
https://hub.docker.com/u/myems

**Comment by liyadongcn** [comment]
use that image on docker hub, why i can not login? i can see the login page . nothing happended when i click the login button. i pulled the image for the api also, but still same

**Comment by guangyuzhang** [comment]
> use that image on docker hub, why i can not login? i can see the login page . nothing happended when i click the login button. i pulled the image for the api also, but still same

Please check IP addresses in .env and nginx.conf, and replace 127.0.0.1 with the actual values outside of docker contianers.

https://github.com/MyEMS/myems/tree/master/myems-api#installation-option-1-install-myems-api-on-docker

**Comment by liyadongcn** [comment]
需要全部安装才能登录吗？现在登录提示红框，但没有文字说明

现在我只安装了的web和api

**Comment by guangyuzhang** [comment]
只安装web和API是可以登录的，可以在浏览器开发者工具（F12）中看一下api调用的返回错误信息，运行容器时注意要在主机目录下创建.env和nginx.conf，并修改文件中的127.0.0.1为宿主机网络中的真实ip地址，因为127.0.0.1在容器中是内部地址

**Comment by liyadongcn** [comment]
与mysql的版本有关吗？我现在用的是5.7.8

好像没有去连接数据库

**Comment by guangyuzhang** [comment]
没有关系
复制example.env文件为 .env文件，127.0.0.1是容器内部地址，修改文件中的IP 127.0.0.1 为真实数据库IP
再把.env文件挂载到容器上，
sudo docker run -d -p 8000:8000 -v /myems-upload:/var/www/myems-admin/upload -v /myems-api/.env:/code/.env:ro --log-opt max-size=1m --log-opt max-file=2 --restart always --name myems-api myems/myems-api

**Comment by liyadongcn** [comment]
这些都应该是按照要求修改了，正确的。


返回的是404

**Comment by guangyuzhang** [comment]
尽量提供一下详细信息，nginx.conf文件

**Comment by liyadongcn** [comment]
APIBaseURL 地址不对造成的，LoginForm.js使用的
 
Config.js 中定义的APIBaseUrl

export const APIBaseURL = window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/api";

打包到docker中运行就变成了 localhost 而不是应该的实际主机地址

**Comment by guangyuzhang** [comment]
export const APIBaseURL = window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/api";
这句话的意思是依据浏览器的地址和端口来访问api，需要在nginx.conf配置api重定向，即使用localhost访问也是没问题的，如下图，所以要检查nginx.conf是否正确。


![image](https://user-images.githubusercontent.com/4197169/195962248-25dd4f0c-daa4-4abc-a2a9-02ece6044994.png)

![image](https://user-images.githubusercontent.com/4197169/195962155-eecea8ae-2d46-4a60-919e-2a6d3b1bf161.png)

**Comment by liyadongcn** [comment]
还是nginx.conf配置的错误

location /api {
            proxy_pass http://192.168.31.185:8000/;
            proxy_connect_timeout 75;
            proxy_read_timeout 600;
            send_timeout 600;
        }
少了8000后的“/”造成的

现在可以登录了

感谢

从 Windows 版邮件发送

发件人: Guangyu Zhang
发送时间: 2022年10月15日 9:07
收件人: MyEMS/myems
抄送: liyadongcn; Comment
主题: Re: [MyEMS/myems] Create Docker Images at Docker Hub (Issue #162)

export const APIBaseURL = window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/api";
这句话的意思是依据浏览器的地址和端口来访问api，需要在nginx.conf配置api重定向，即使用localhost访问也是没问题的，如下图，所以要检查nginx.conf是否正确。
