### ISSUE TITLE
After install MyEMS have problem to login

### ISSUE THREAD

**Issue by sdepascali** [MyEMS/myems#236]
Hi all

I have try to install over Docker-compose MyEMS and all is working i can access to :8000, :8001/version and also to :80. My problem is i can't access to the platform with administrtor/!MyEMS1. Any advice what  kind of mistake i made.

kind regards
salva

**Comment by guangyuzhang** [comment]
Please check all nginx.conf files and .env files, and make sure that you have modied the default ip addresses to your actual addresses. Note that 127.0.0.1 is the internal address of container and should be changed.

**Comment by sdepascali** [comment]
Hi Guangyuzhang is still have the same problem any more advice.
[MyEMS install problem.pdf](https://github.com/MyEMS/myems/files/8839688/MyEMS.install.problem.pdf)

One more question i am interested to use the Enterprise-edition because my device is using mqtt or http. Any advice on this. The idea is to use MyEMS with blockchain.

Thanks in advance
Salva

**Comment by sdepascali** [comment]
All are using the same IP address maybe is this the problem?

**Comment by sdepascali** [comment]
I have installed MYSQL on docker and imported dataschema and now it works

**Comment by abdulhadi214** [comment]
Hi all...
I have tried to install myems according to the existing guide, but when I run it and try to log in it always fails even though the user and password are correct.

Is there a video tutorial for installing and logging in...?
![image](https://github.com/MyEMS/myems/assets/14899328/d115eebe-3ec3-46ba-afba-dcf1f65f5d30)

**Comment by nengyuanzhang** [comment]
Replace 127.0.0.1:8000 in nginx.conf with actual HOST IP address and port of myems-api

**Comment by Sudococommunity** [comment]
Same error

**Comment by Sudococommunity** [comment]
How you installed mysql in docker

**Comment by nengyuanzhang** [comment]
> How you installed mysql in docker

Don't install mysql in docker

> Same error

replace 127.0.0.1 with physical computer's network card's IP address

**Comment by Sudococommunity** [comment]
I did that replaced 127.0.0.1 with actual network card still there is an login error
