### ISSUE TITLE
Please check all nginx.conf files and .env files, and make sure that you have modied the default ip addresses to your actual addresses. Note that 127.0.0.1 is the internal address of container and should be changed.

### ISSUE THREAD

**Issue by sdepascali** [MyEMS/myems#237]
Please check all nginx.conf files and .env files, and make sure that you have modied the default ip addresses to your actual addresses. Note that 127.0.0.1 is the internal address of container and should be changed.

_Originally posted by @guangyuzhang in https://github.com/MyEMS/myems/issues/236#issuecomment-1146573365_

**Comment by sdepascali** [comment]
I have installed now mysql on docker and now it works.

One more question i am interested to use the Enterprise-edition because my device is using mqtt or http. Any advice on this. The idea is to use MyEMS with blockchain.

Thanks in advance
Salva

**Comment by Sudococommunity** [comment]
I am having same issue 🥲 I changed all 127.0.0.1 to my ip address  still having login problem
