### ISSUE TITLE
How to use enterprise edition?

### ISSUE THREAD

**Issue by sdepascali** [MyEMS/myems#239]
Hi I am interested to use enterprise edition how?

**Comment by guangyuzhang** [comment]
Hi, @sdepascali, what's features do you need besides MyEMS Community Edition?

**Comment by sdepascali** [comment]
Hi Zhang

Right now I am on holiday but features that I am interested to connecting device over mqtt and http. Myems have also a mobile for end user.

Thank in advance
Salva

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
