### ISSUE TITLE
配电系统数据点bug

### ISSUE THREAD

**Issue by Hugh-Jie** [MyEMS/myems#242]
原始代码：myems\myems-admin\core\distributioncircuit.py 405-413

原始代码好像无法显示配电系统的绑定数据点，修改之后就可以显示了，是不是代码的bug？
原始代码是下面注释的

`        distribution_system_dict = dict()
        if rows_distribution_systems is not None and len(rows_distribution_systems) > 0:
            for row in rows_distribution_systems:
                # distribution_system_dict[row['uuid']] = {"id": row[0],
                #                                          "name": row[1],
                #                                          "uuid": row[2]}
                distribution_system_dict[row['uuid']] = {"id": row[0],
                                                         "name": row[1],
                                                         "uuid": row[2]}`

**Comment by guangyuzhang** [comment]
感谢反馈，经查并没有发现您说的问题，请确认本地代码版本及是否修改过

**Comment by Hugh-Jie** [comment]
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/50091924/174516461-7beee2e5-fa70-4660-be4e-9cabe8c449c5.png">
<img width="906" alt="image" src="https://user-images.githubusercontent.com/50091924/174516483-dd7d5897-8392-445d-afd4-8107ff7ae0e8.png">
您好，这应该是我的报错信息及代码位置。所以我修改的此处的代码。请问下现在github上是最新的源码吗？

**Comment by guangyuzhang** [comment]
感谢反馈，已经修复，github是最新的，请重新拉取一下
