### ISSUE TITLE
admin组件,添加虚拟表bug

### ISSUE THREAD

**Issue by kkomia** [MyEMS/myems#260]
特定情况下添加变量的表和表类型不匹配

![1660110740(1)](https://user-images.githubusercontent.com/74851565/183825637-b069525f-7a29-48f9-aaac-2878c4c42373.jpg)

并且参数能够添加成功,如下图 (保存虚拟表会失败)

![1660110929(1)](https://user-images.githubusercontent.com/74851565/183826416-18a16748-6887-495f-90cc-9b568324e591.jpg)

问题复现步骤,  选择表类型->选择表->再次更改表类型->点击添加

**Comment by guangyuzhang** [comment]
fixed
