### ISSUE TITLE
Need advice for how to config MyEMS admin to listen to receive data from iot device via websocket

### ISSUE THREAD

**Issue by riahtu** [MyEMS/myems#5]
Hi, I need you provide me some example or information, how to config MyEMS admin or how to settings sevice module to listen to receive data that push from iot devices via tcp socket or websocket.
 
Thank you,
Uthai

**Comment by guangyuzhang** [comment]
Hi @riahtu 

1. Login MyEMS admin
2. Go to System Settings | Gateway Settings
3. Click 'Add Gateway' to add a gateway, click 'Save' then copy the ID and Token for configuring myems-modbus-tcp service.
4. Go to System Settings | Data Source Settings
5. Click 'Add Data Source' to add a datasource, the default tab is 'Data Source'
6. Select the Gateway created in Step 3, input 'modbus-tcp' for Protocol, input '{"host":"192.168.9.101","port":502}' for Connection, change the IP address and Port according to your Modbus device.
7. Click the 'Point' tab of Data Source Settings, select the datasource created in Step 6.
8. Click 'Add Point' to create a point. 
9. In the 'Object Type' dropdown list, 'ENERGY_VALUE' is an incremental energy consumption value of parameter of a meter, 'ANALOG_VALUE' is time-varying "quantities" (voltage, current, etc.), and 'DIGITAL_VALUE' must have a finite set of possible values. The number of values in the set can be anywhere between two and a-very-large-number-that's-not-infinity. Most commonly digital signals will be one of two values -- like either 0V or 5V. Timing graphs of these signals look like square waves.
10. If 'Is Trend' is checked, the value will be saved to the historical database(myems_historcial_db)
11. In 'Address(JSON)' area, for 'modbus-tcp' protocol, please use the template below,
`{"byte_swap":true,"format":"<l","function_code":3,"number_of_registers":2,"offset":6401,"slave_id":1}`
'byte_swap' for Byte Swapping
'format': refer to [Format Strings](https://docs.python.org/3/library/struct.html#format-strings)

12. Once you have add all Gateways, Data Sources and Points, please update config.py under myems_modbus-tcp and then install and start the myems_modbus_tcp service. Refer to [myems_modbus_tcp](https://github.com/MyEMS/myems/blob/master/myems-modbus-tcp/README.md)


Thanks for using MyEMS

**Comment by riahtu** [comment]
Thank you ,

Uthai Roemtrakul

On 22 Feb BE 2564, at 21:36, Guangyu Zhang <notifications@github.com> wrote:

﻿

Hi @riahtu<https://github.com/riahtu>

  1.  Login MyEMS admin

  2.  Go to System Settings | Gateway Settings

  3.  Click 'Add Gateway' to add a gateway, click 'Save' then copy the ID and Token for configuring myems-modbus-tcp service.

  4.  Go to System Settings | Data Source Settings

  5.  Click 'Add Data Source' to add a datasource, the default tab is 'Data Source'

  6.  Select the Gateway created in Step 3, input 'modbus-tcp' for Protocol, input '{"host":"192.168.9.101","port":502}' for Connection.

  7.  Click the 'Point' tab of Data Source Settings, select the datasource created in Step 6.

  8.  Click 'Add Point' to create a point.

  9.  In the 'Object Type' dropdown list, 'ENERGY_VALUE' is an incremental energy consumption value of parameter of a meter, 'ANALOG_VALUE' is time-varying "quantities" (voltage, current, etc.), and 'DIGITAL_VALUE' must have a finite set of possible values. The number of values in the set can be anywhere between two and a-very-large-number-that's-not-infinity. Most commonly digital signals will be one of two values -- like either 0V or 5V. Timing graphs of these signals look like square waves.

  10. If 'Is Trend' is checked, the value will be saved to the historical database(myems_historcial_db)

  11. In 'Address(JSON)' area, for 'modbus-tcp' protocol, please use the template below,
{"byte_swap":true,"format":"<l","function_code":3,"number_of_registers":2,"offset":6401,"slave_id":1}
'byte_swap' for Byte Swapping
'format': refer to Format Strings<https://docs.python.org/3/library/struct.html#format-strings>

  12. Once you have add all Gateways, Data Sources and Points, please update config.py under myems_modbus-tcp and then install and start the myems_modbus_tcp service. Refer to myems_modbus_tcp<https://github.com/MyEMS/myems/blob/master/myems-modbus-tcp/README.md>

Thanks for using MyEMS

**Comment by guangyuzhang** [comment]
Close this issue and the docs will be enhanced.
